apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cadvisor
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 2s
        factor: 2
        maxDuration: 1m
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://ckotzbauer.github.io/helm-charts
    chart: cadvisor
    targetRevision: 2.2.4
    helm:
      values: |
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          effect: "NoSchedule"
        - key: "node-type"
          operator: "Equal"
          value: "cloud"
          effect: "NoSchedule"
        container:
          port: 8080
          additionalArgs:
            - --storage_duration=1m30s
            - --housekeeping_interval=10s
            - --max_housekeeping_interval=15s
            - --event_storage_event_limit=default=0
            - --event_storage_age_limit=default=0
            - --enable_metrics=cpu,cpuLoad,disk,diskIO,memory,oom_event,network
            - --store_container_labels=false
            - --docker_only
            - --disable_root_cgroup_stats=false
            - --enable_load_reader=false
            - --whitelisted_container_labels=io.kubernetes.container.name,io.kubernetes.pod.name,io.kubernetes.pod.namespace
          hostPaths:
            - name: rootfs
              path: "/"
              mount: "/rootfs"
            - name: varrun
              path: "/var/run"
            - name: sys
              path: "/sys"
            - name: docker
              path: "/var/lib/docker"
            - name: disk
              path: "/dev/disk"
        metrics:
          enabled: false
          interval: 30s
          scrapeTimeout: 30s
          labels:
            release: prometheus
          metricRelabelings:
          - sourceLabels:
            - container_label_io_kubernetes_pod_name
            targetLabel: pod
          - sourceLabels:
            - container_label_io_kubernetes_container_name
            targetLabel: container
          - sourceLabels:
            - container_label_io_kubernetes_pod_namespace
            targetLabel: namespace
          - action: labeldrop
            regex: container_label_io_kubernetes_pod_name
          - action: labeldrop
            regex: container_label_io_kubernetes_container_name
          - action: labeldrop
            regex: container_label_io_kubernetes_pod_namespace
          port: http
          relabelings:
          - sourceLabels:
            - __meta_kubernetes_pod_node_name
            targetLabel: node
          - sourceLabels:
            - __metrics_path__
            targetLabel: metrics_path
            replacement: /metrics/cadvisor
          - sourceLabels:
            - job
            targetLabel: job
            replacement: kubelet
