apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'airflow-test'
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  source:
    repoURL: 'https://bitnami222.github.io/bitnami'
    targetRevision: latest
    chart: airflow
    helm:  
      values: |
        resources:
          limits:
            cpu: 3
            memory: 1024Mi
        postgresql:
          enabled: true
          auth:
            enablePostgresUser: true
            username: airflow
            password: "oracle"
            database: dbairflow
            existingSecret: ""
          architecture: standalone
          primary:
          resources:
            requests:
              limits:
                cpu: 2
                memory: 2048Mi
  
