apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'airflow'
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: 'https://airflow.apache.org'
    targetRevision: latest
    chart: airflow
    helm:  
      values: |

