apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'airflow-test'
spec:
  project: default
  source:
    repoURL: 'https://airflow.apache.org'
    targetRevision: 1.12.0
    helm:
      releaseName: airflow-test
      version: v3
    chart: airflow
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    source:
      repoURL: https://bitnami.github.io/bitnami
      chart: airflow
      targetRevision: 2.2.4
      helm:
        values: 
