apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'airflow-test'
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  source:
    repoURL: 'https://airflow.apache.org'
    targetRevision: 1.12.0
    chart: airflow
    helm:
      releaseName: airflow-test
      version: v3
      values: |
